# Generated by Django 4.2.20 on 2025-03-20 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_added',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 3, 20, 23, 16, 7, 626939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='todo',
            name='due',
            field=models.DateField(default=datetime.datetime(2025, 3, 20, 23, 16, 53, 427741, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
